# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: switchback.bike
url: https://www.switchback.bike
baseurl: ""

title: Switchback Bicycle Repair
email: info@switchback.bike
description: Switchback Bicycle Repair is a mobile bike work shop that operates between Bellingen and South West Rocks, NSW. I come to you, taking the hassle out of servicing your bike.
author: VOID Digital
logo:
  path: assets/img/logo.webp
  height: 60

locale: "en-AU"

markdown: kramdown
