domain: switchback.bike
url: https://www.switchback.bike
baseurl: ""

title: Switchback Bicycle Repair
description: Switchback Bicycle Repair is a mobile bike work shop that operates between Bellingen and South West Rocks, NSW. I come to you, taking the hassle out of servicing your bike.
author: VOID Digital
logo:
  path: assets/img/logo.webp
  height: 60

locale: "en-AU"

markdown: kramdown
